### PR TITLE
#144 Fix sort by in IE10

### PR DESCRIPTION
**Pull request by wilr**
IE10 does not support dataset. An alternative approach is required for IE.

### CODE REVIEW

**Comment by tractorcow** [comment]
No changes to dist files?

**Comment by wilr** [comment]
Yeah sorry I still getting used to including dist in commits, normally leave out to avoid conflicts. Checked out branch and ran `npm build`.

**Comment by sminnee** [comment]
Yeah, we need dist files in the build if we want to avoid forcing *every* SilverStripe user to also install npm.

**Comment by tractorcow** [comment]
@wilr I've only just given you access to the repo, but please use the open-sausages fork; This lets other teammembers rebase / rebuild your PR as necessary. :)

In the mean time, rebase please!

**Comment by wilr** [comment]
Looks like some major refactoring since 42f91b46 so closing as I think the issue will be resolved.

**Pull request closed without merging**
