### PR TITLE
FIX Button alignment tweaks

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-asset-admin/issues/896

### CODE REVIEW

**Comment by emteknetnz** [comment]
If we align the buttons then there's an issue with the hover state being "cut off"

image

image

We could still align it and have the hover state will "go over", though this may look worse

image

However we actually already do this for the search button on the "Pages" section in the CMS

image

This is how it looks at present:

image

image

@sachajudd how would you like to proceed with this?

**Comment by emteknetnz** [comment]
The new icon looks, which is already used on small breakpoints, does look a little odd to me - would you like to keep this @sachajudd?

image

**Comment by sachajudd** [comment]
> The new icon looks, which is already used on small breakpoints, does look a little odd to me - would you like to keep this @sachajudd?
> 
> image

In Jared's design he is recommending completely dropping the text and replacing to use the icon. It's a well known icon, you don't need the text beside it. 

In your other hover issues you're having I'm unsure why your hover is being cut off and isn't moving with the whole toolbar? We will need to catch up so I can see it visually. Set a meeting in my calendar and you can show me a demo.

**Comment by emteknetnz** [comment]
@sachajudd have updated the sort icon

image

**Review by sachajudd — APPROVED** [review]
I've approved this from a UX perspective. Someone will need to pull down and test the UI with the code though. Nice one Steve 🙂

**Review by bergice — CHANGES_REQUESTED** [review]
Tests need to be fixed.

**Comment by emteknetnz** [comment]
@bergice Tests have been fixed

**Pull request merged**
