### PR TITLE
List view for gallery

### PR DESCRIPTION
**Pull request by flamerohr**
This adds a list view (GridField type table view) for gallery items, to contrast with the default thumbnail view that is currently in place.

See https://github.com/silverstripe/silverstripe-asset-admin/issues/278 for more details

requires https://github.com/silverstripe/silverstripe-framework/pull/6371 to be merged first

### CODE REVIEW

**Comment by tractorcow** [comment]
Better than a listing gallley

**Comment by tractorcow** [comment]
There's a missing progress indicator when uploading files in gallery view.

Files also temporarily display `NaN GB` as files size.

**Comment by tractorcow** [comment]
When toggling between two states, shouldn't we show these as side-by-side tabs, rather than just the current icon?

image

Something similar to 

image

**Comment by tractorcow** [comment]
I've added a fix for griddle re-sorting values. I'll let you fix the upload progress indicator. :)

**Comment by flamerohr** [comment]
I've added the progress bar and fixed the NaN issue

**Comment by tractorcow** [comment]
Merged framework, restarted tests.

**Comment by flamerohr** [comment]
thanks for fixing the behat tests @tractorcow, looking good :)

**Pull request merged**
