### PR TITLE
implode in _t() breaks i18nTextCollectorTask

### PR DESCRIPTION
**Pull request by lpostiglione**
implode in _t() breaks i18nTextCollectorTask

### CODE REVIEW

**Comment by Cheddam** [comment]
Hey @lpostiglione, thanks for raising this PR! Since it's a fix with no new functionality, it makes sense to target it to the `4.5` branch rather than the `4` branch, so that it can be included in the next patch release (`4.5.1`). Would you be able to retarget it?

**Comment by brynwhyman** [comment]
@Cheddam I think you meant to say:
> it makes sense to target it to the ~4~ 1.5 branch rather than the ~4~ 1 branch, so that it can be included in the next patch release ~(4.5.1)~ (1.5.1). Would you be able to retarget it?

**Comment by lpostiglione** [comment]
@Cheddam @brynwhyman 

I am no GitHub expert but I feel like what I did is not exactly a good idea?

Maybe you could tell me how to retarget this correctly?

**Comment by Cheddam** [comment]
@lpostiglione Since you raised this directly via GitHub, it might be easiest to raise a new PR by making the change directly to the `1.5` branch. Otherwise, if you're confident enough to use the command line, you can clone your fork of the repository and rebase your branch onto `1.5` by hand using the following commands:

```
git clone git@github.com:lpostiglione/silverstripe-asset-admin.git
cd silverstripe-asset-admin
git checkout patch-1
git rebase --onto=1.5 HEAD~1
git push --force-with-lease
```

**Comment by lpostiglione** [comment]
@Cheddam Thank you very much, should be ready now.

**Pull request merged**
