### PR TITLE
API Remove reference to removed constructExtensions()

### PR DESCRIPTION
**Pull request by tractorcow**
Parent story https://github.com/silverstripe/silverstripe-framework/issues/6210

### CODE REVIEW

**Comment by tractorcow** [comment]
Need to merge in the phpunit / php version change.

**Comment by robbieaverill** [comment]
Just came across this in 1.0 as well - do you think this is an API change? I can't see it breaking anything

**Comment by tractorcow** [comment]
Not really I guess; it's more updating to respond to API changes elsewhere.

**Comment by tractorcow** [comment]
This was actually done up in 4.0 branch so it's not necessary to do here also.

**Pull request closed without merging**
