### PR TITLE
Update class namespace for campaign admin

### PR DESCRIPTION
**Pull request by tractorcow**
See https://github.com/silverstripe/silverstripe-framework/issues/6735

### CODE REVIEW

**Comment by sminnee** [comment]
Needs a rebase — looks like it'll become a 1 line change.

**Comment by tractorcow** [comment]
done.

**Comment by chillu** [comment]
Given the `asset-admin` module depends on campaign admin functionality, should they require it in `composer.json`? e.g. for `AddToCampaignHandler`

**Comment by chillu** [comment]
Damian agrees that we need that dependency, so I've added it here.

**Comment by sminnee** [comment]
OK that's tolerable for now – i.e. doesn't block merge – but a weird piece of coupling.

**Comment by tractorcow** [comment]
In the future we can de-couple it with a few class_exists(), or maybe just an extension hook.

**Pull request merged**
