### PR TITLE
MINOR: Add missing file upload progress bar bg

### PR DESCRIPTION
**Pull request by lukereative**
Related Issue: #266

### CODE REVIEW

**Comment by flamerohr** [comment]
@clarkepaul @newleeland this pull request adds a grey background for the progress bar, so that you can clearly see the progress when there is a low percentage.

What do you guys think about having this background for the bar?
I think it's a good addition.

**Comment by clarkepaul** [comment]
Yup I think thats a good idea, it was in the designs so not sure if it was missed intially? 
image

**Comment by tractorcow** [comment]
Needs a rebase. rc1 please. :)

**Comment by flamerohr** [comment]
behat tests failing are not related, so I'll merge

**Pull request merged**
