### PR TITLE
FIX Only exclude Folders from the used on table instead of all Files

### PR DESCRIPTION
**Pull request by emteknetnz**

### CODE REVIEW

**Review by maxime-rainville — APPROVED** [review]
Looks good. Wait for the 1.7 branch to be created and retarget there. 

Are you sure the commit prefix shouldn't be BUG? Looks like your tweaking the actual behaviour.

**Comment by emteknetnz** [comment]
I've updated the commit message to FIX

**Review by Cheddam — APPROVED** [review]

**Comment by emteknetnz** [comment]
Silverstripe travis currently has a very large backlog
Green on cc's travis
https://travis-ci.com/github/creative-commoners/silverstripe-asset-admin/builds/198072775

**Review by dnsl48 — DISMISSED** [review]
> Looks good. Wait for the 1.7 branch to be created and retarget there.

Are you planning to retarget the PR to 1.7 so we don't have to backport it later?

**Pull request merged**
