### PR TITLE
BUG Fix wrong cursors for error asset thumbnails

### PR DESCRIPTION
**Pull request by phalkunz**
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/559

### CODE REVIEW

**Comment by phalkunz** [comment]
@assertchris Thanks :) I've updated the pull request.

**Comment by flamerohr** [comment]
@phalkunz I still get the pointer cursor when I hover over the red cross area.

I think `.gallery-item__checkbox-label` and `.gallery-item__checkbox-label:before` requires that cursor styling as well.

**Comment by phalkunz** [comment]
@assertchris The red cross area should use pointer cursor because the user can click it to cancel/dismiss the message. The last point in the **should** heading says "_we use the pointer cursor when hovering over the cancel upload X_"

**Comment by flamerohr** [comment]
@phalkunz make sure to tag the right Chris lol

Ah sorry, I missed that point, but maybe the blank area bottom right of the cross should have that `not_allowed` cursor though? At the moment, the bottom right area is still default.

**Comment by phalkunz** [comment]
Good testing :) @flamerohr

**Pull request merged**
