### PR TITLE
Remove Default DropzoneJS Timeout of 30s

### PR DESCRIPTION
**Pull request by HARVS1789UK**
Resolves issue 977 (see - https://github.com/silverstripe/silverstripe-asset-admin/issues/977) where file uploads of over 30s have the network request fail (marked as "(cancelled)" in dev tools) due to DropzoneJS having a default client-side timeout of 30 seconds.

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
It would be a reasonably "quick win" solution to have this in config. See:

https://github.com/silverstripe/silverstripe-asset-admin/blob/1.2/code/Controller/AssetAdmin.php#L259-L268

These appear to automatically filter down to `AssetDropzone` via the `options` prop. See:

https://github.com/silverstripe/silverstripe-asset-admin/blob/b318caa0f52c3b704b679064499dc434f1c234f1/client/src/containers/Gallery/Gallery.js#L893

and

https://github.com/silverstripe/silverstripe-asset-admin/blob/b318caa0f52c3b704b679064499dc434f1c234f1/client/src/containers/Gallery/Gallery.js#L940

**Comment by kinglozzer** [comment]
@ScopeyNZ Is there an equivalent option for `UploadField`?

**Comment by ScopeyNZ** [comment]
Ah good point. Hmmmn that's kind of annoying.

**Comment by kinglozzer** [comment]
I think we should introduce that to the `UploadField` API though (it’d also solve https://github.com/silverstripe/silverstripe-asset-admin/issues/925), let’s create a separate issue for that

**Comment by ScopeyNZ** [comment]
Are you raising an issue for that or should I?

**Comment by kinglozzer** [comment]
@ScopeyNZ I think you have a better grasp of client-side stuff than me, so go for it 😃

**Comment by ScopeyNZ** [comment]
Done: https://github.com/silverstripe/silverstripe-asset-admin/issues/986

**Pull request merged**
