### PR TITLE
Fix link to documentation

### PR DESCRIPTION
**Pull request by martinduparc**

### CODE REVIEW

**Comment by sminnee** [comment]
This should remain a relative link. If there is a webpage is breaking on this, which one is it?

**Comment by martinduparc** [comment]
If you look at the [main repo page](https://github.com/silverstripe/silverstripe-asset-admin), the link to the documentation is broken.

**Comment by sminnee** [comment]
Keep it relative but remove introduction.md

**Comment by martinduparc** [comment]
I've updated my branch. Can you reopen the PR so that the changes are visible.

**Comment by sminnee** [comment]
Looks good, thanks for that!

**Pull request merged**
