### PR TITLE
FIX Reset apollo store when deleting a file to ensure item is removed from the UI

### PR DESCRIPTION
**Pull request by robbieaverill**
The optimistic cache update logic was broken since SilverStripe 4.3.x. While this is not a great workaround, it at least ensures that the functionality works correctly. Optimistic updates can be re introduced again later in a way that is compatible with injectable GraphQL queries.

Fixes https://github.com/silverstripe/silverstripe-asset-admin/issues/852 and the Behat builds in 1.4 once merged up.

## Dependencies
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/889

## Todo
- [x] Get tests passing (should just be a matter of adding `getApolloHOC()`
- [ ] ~~Separate PR for the 1.4 branch using node 10.~~

### CODE REVIEW

**Comment by unclecheese** [comment]
After some thought, there's a way to accomplish this without nuking the optimistic update. It requires a slight change to the `apolloGraphQLContainer` where the factory is actually a proxy object that allows the user to consume either the HOC or the AST (both injected).

I've added notes to the OP.

**Comment by robbieaverill** [comment]
Thanks for your work @unclecheese, I'll come back to it this week if you don't beat me to it =)

**Comment by unclecheese** [comment]
This is good to go. As mentioned on the dependent PR, we'll worry about the separate node 10 build on merge up. There will be conflicts in `dist/` anyway.

**Comment by chillu** [comment]
Moving this to blocked, since @unclecheese wasn't comfortable putting this into the pending 4.4.1 release (it can go into a 4.4.2 soon after)

**Pull request merged**
