### PR TITLE
Fix image being small when dragging a folder

### PR DESCRIPTION
**Pull request by bergice**
Issue: https://github.com/silverstripe/silverstripe-asset-admin/issues/902

### CODE REVIEW

**Comment by robbieaverill** [comment]
Could you are a screenshot or a little screen capture to show this in action?

**Comment by bergice** [comment]
@robbieaverill 

image

**Comment by newleeland** [comment]
> @robbieaverill
> 
> image

Hey @bergice. Not quite sure how large you are recommending the dragged item should be. But we intentionally made the dragged item to be smaller than the original item. This was to ensure the items in the background are visible so that the user can see where they are dragging into. 

This was the original design:
Screen Shot 2019-06-04 at 10 45 53 AM

**Comment by bergice** [comment]
@newleeland the dragged item size has not changed, just the icon inside it.

**Comment by ScopeyNZ** [comment]
(Pre-existing behat failures)

**Pull request merged**
