### PR TITLE
Create hr_HR

### PR DESCRIPTION
**Pull request by hdpero**
Croatian translation for label.

### CODE REVIEW

**Comment by tractorcow** [comment]
Hi @hdpero, thank you very much for your contribution!

I've created a croatian locale on transifex at https://www.transifex.com/silverstripe/silverstripe-asset-admin/language/hr/.

Would you be able to assist us with further translations? I would like to make you a manager for this locale, but you'd need a transifex account first.

image

**Comment by hdpero** [comment]
Hi @tractorcow , yes, I would like that. I already have Transifex account, but I couldn't find asset-admin module, but now I have found it and I sent request to join Croatian translation team.

**Comment by tractorcow** [comment]
What is your transifex account name? did you get added?

**Comment by tractorcow** [comment]
I've added `Petar Simic` to reviewers :D

**Pull request closed without merging**
