### PR TITLE
Fix ambiguous UploadField labels

### LINKED ISSUE #765: Reword "Browse or Add from files"
Can I propose rewording the "**Browse**" and "**Add from files**" links on the Upload field?

I just feel that the current wording is a bit ambiguous, especially to less "savvy" CMS users.  "Browse" could mean "Browse the files in the CMS" or "Browse files on your computer", and "Add from files" could mean "Add from files in the CMS" or "Add from files on your computer".

How about:
"**Upload** or **Add from 'Files'**"

Open to other suggestions. Ideally, it should be:
* Short and succinct
* Clear as to if it's locating files on the user's computer or already uploaded files
* Shouldn't mention "Computer", as we could be on an iPad / smartphone.

The "Upload" label is used for this exact action within the Files area and modal, so using it here would also improve consistency.

I don't like the "From the CMS" wording that SS3 used, as the files don't really belong to the CMS.

While capitalising the 'F' on "Files" may slightly more associate it with the CMS's "Files" area, I don't think it's quite enough.

### PR DESCRIPTION
**Pull request by jonom**
‘Browse’ could mean your computer or the CMS File store. Likewise for ‘Add from files’, particularly since the word ‘Add’ implies a new file is being introduced to the system rather than a previous upload being reused. Fixes #765

@robbieaverill I did `yarn install` and `yarn build` in the root and got a ton of error messages. Is there a trick here? Or do builds happen somewhere else?

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
As long as you `yarn;yarn build` from the root of `asset-admin` it should work. Ensure you're using the right version of `node` - `nvm` (node version manager) is your friend for this. For the `1` branch the version of node required is `10`.

cc @silverstripeux

**Comment by jonom** [comment]
Thanks @ScopeyNZ - is this standard for all SS react projects? Is it documented somewhere and could we link to it from the contributing section of the ReadMe?

**Comment by ScopeyNZ** [comment]
Hit the wrong button sorry

This is standard for SS projects, and any npm/yarn project. We try to help out by specifying the node version required in `package.json` and `.nvmrc`. In saying that - our docs could always do with updating to help understanding for this 😅

**Comment by jonom** [comment]
Thanks @ScopeyNZ, I installed nvm and switched to v10, still bombed. Here's a sample:

```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit ([redacted]/asset-admin/node_modules/node-sass/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "[redacted]/.nvm/versions/node/v10.16.0/bin/node" "[redacted]asset-admin/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd [redacted]asset-admin/node_modules/node-sass
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.6.2
```

Any chance you could do that part, if you're happy with this change?

**Comment by ScopeyNZ** [comment]
Yep sure. We can do the build for you. I'll wait for some feedback from the UX team and @robbieaverill for the translation tag usage - he might not want the tags changed so that we don't lose translation coverage.

**Comment by jonom** [comment]
> he might not want the tags changed so that we don't lose translation coverage.

Sure. I was inclined to use the existing tags for that same reason but @robbieaverill and @maxime-rainville thought it was probably safer to use new ones.

**Comment by jonom** [comment]
> We can do the build for you

Thanks!

**Comment by maxime-rainville** [comment]
I've rebuilt the client lib which should make the travis green.

**Comment by robbieaverill** [comment]
Behat failure is pre-existing

**Comment by jonom** [comment]
Thanks for the build and merge 👍

**Pull request merged**
