### PR TITLE
FIX Ensure fresh options are passed to dropzone

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-asset-admin/issues/1352

Reverts part of this commit - https://github.com/silverstripe/silverstripe-asset-admin/commit/45e7461a549ae858999eacd8d11eaeb4bbe13515#

### CODE REVIEW

**Review by ChloeSartorelli — CHANGES_REQUESTED** [review]
The behat test passes even without the fix - please update the behat test so that it fails without the fix, but passes with it (probably explicitly check that "You can not upload any more files." is not there after uploading the second file)

**Comment by emteknetnz** [comment]
I don't think this is possible unfortunately.

This regression only happens when you click "Upload new" rather that "Choose existing', and you select a file from the (native) file selector dialog.

Unfortunately there isn't a way to get behat to "select a file from the file selector" - when you get behat to click "Upload new", there is no file selector, though the link "Upload new" is underlined.

There are no existing tests where "Upload new is clicked", in fact all the "upload" tests will "Choose existing" i.e. pre-uploaded files - so I'm not the first person to run into this issue.

I think we'll just have to make do with the behat test as it is.

**Comment by ChloeSartorelli** [comment]
Bugger. Well, we can't win em all 😅

**Review by ChloeSartorelli — APPROVED** [review]
Works great locally.

**Pull request merged**
