### PR TITLE
Add scss-lint rules (in addition to sass-lint)

### PR DESCRIPTION
**Pull request by chillu**
Followup from https://github.com/silverstripe/silverstripe-asset-admin/pull/115

https://github.com/brigade/scss-lint is used on CodeClimate
(https://docs.codeclimate.com/docs/scss-lint), which we've started [using](https://codeclimate.com/github/silverstripe/silverstripe-asset-admin/issues?category=&engine=scss-lint) recently.

https://github.com/sasstools/sass-lint isn't supported by CodeClimate yet,
but does mean we can run "npm run lint" without relying on yet another
package manager and runtime (Ruby+Rubygems for scss-lint).
Note that CodeClimate support is under discussion at
https://github.com/sasstools/sass-lint/issues/9

Assuming we want both CI and local developer ergonomics, we can't really choose a single one.

A one-way converter exists for `.scss-lint.yml`
to `.sass-lint.yml` (http://sasstools.github.io/make-sass-lint-config/).

It's not an ideal situation, but I think we can get the configurations sufficiently synced up for it to be rarely a problem in practice. I've improved Sam's `.sass-lint.yml` a bit, by manually "merging in" the `.scss-lint.yml` defaults with the AirBnB specific ones. This resulted in a few rules being added to the auto-generated `.sass-lint.yml`, and means the linting output is more in line with each other.

I've also disabled linting on `AssetAdmin.scss` since those are legacy styles we shouldn't really spend much energy on getting in line with the linting standards.

scss-lint

```
client/src/components/BulkActions/BulkActions.scss:11 [E] ColorVariable: Color literals like `rgba(0, 0, 0, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/BulkActions/BulkActions.scss:38 [E] BemDepth: BEM selectors should have no more than 1 element, but `gallery__bulk-actions__counter` has 2
client/src/components/BulkActions/BulkActions.scss:44 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/BulkActions/BulkActions.scss:73 [E] ColorVariable: Color literals like `rgba(0, 0, 0, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/BulkActions/BulkActions.scss:90 [E] ColorVariable: Color literals like `rgba(0, 0, 0, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/Dropzone/Dropzone.scss:15 [E] ColorVariable: Color literals like `rgba(236, 239, 241, 0.9)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:17 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:34 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:43 [E] ColorVariable: Color literals like `#ddd` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:56 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:74 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:82 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:88 [E] BemDepth: BEM selectors should have no more than 1 element, but `item__actions__action` has 2
client/src/components/File/File.scss:88 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:95 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:96 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:101 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:102 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:107 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:108 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:113 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:114 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:119 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:120 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:127 [E] BemDepth: BEM selectors should have no more than 1 element, but `item__actions__action--select` has 2
client/src/components/File/File.scss:127 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:129 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:140 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:157 [E] BemDepth: BEM selectors should have no more than 1 element, but `item__actions__action` has 2
client/src/components/File/File.scss:170 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:178 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:184 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:185 [E] ColorVariable: Color literals like `#ddd` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:193 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:197 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/components/File/File.scss:211 [E] ColorVariable: Color literals like `#ddd` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:217 [E] ColorVariable: Color literals like `#29abe2` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/components/File/File.scss:240 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/containers/Gallery/Gallery.scss:27 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:28 [E] ColorVariable: Color literals like `rgba(0, 0, 0, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/containers/Gallery/Gallery.scss:31 [E] SelectorDepth: Selector should have depth of applicability no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:31 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:35 [E] SelectorDepth: Selector should have depth of applicability no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:43 [E] ColorVariable: Color literals like `rgba(0, 0, 0, 0.2)` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/containers/Gallery/Gallery.scss:48 [E] SelectorDepth: Selector should have depth of applicability no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:48 [E] NestingDepth: Nesting should be no greater than 3, but was 4
client/src/containers/Gallery/Gallery.scss:69 [E] BemDepth: BEM selectors should have no more than 1 element, but `gallery__load__more` has 2
client/src/containers/Gallery/Gallery.scss:71 [E] ColorVariable: Color literals like `#fff` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/containers/Gallery/Gallery.scss:78 [E] ColorVariable: Color literals like `#338dc1` should only be used in variable declarations; they should be referred to via variable everywhere else.
client/src/containers/Gallery/Gallery.scss:86 [E] ImportantRule: !important should not be used
```

sass-lint

```
client/src/components/BulkActions/BulkActions.scss
  11:25  warning  Color functions such as 'rgba' should only be used in variable declarations                       no-color-literals
  38:4   error    Selector '.gallery__bulk-actions__counter' should have 1 or fewer BEM elements, but 2 were found  bem-depth
  44:12  warning  Color literals such as 'fff' should only be used in variable declarations                         no-color-literals
  73:29  warning  Color functions such as 'rgba' should only be used in variable declarations                       no-color-literals
  90:25  warning  Color functions such as 'rgba' should only be used in variable declarations                       no-color-literals

client/src/components/Dropzone/Dropzone.scss
  15:17  warning  Color functions such as 'rgba' should only be used in variable declarations  no-color-literals

client/src/components/File/File.scss
    8:17  warning  Color functions such as 'rgba' should only be used in variable declarations                      no-color-literals
   17:12  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
   34:23  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
   43:29  warning  Color literals such as 'ddd' should only be used in variable declarations                        no-color-literals
   88:8   error    Selector '.item__actions__action' should have 1 or fewer BEM elements, but 2 were found          bem-depth
   96:21  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  102:21  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  108:21  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  114:21  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  120:21  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  127:8   error    Selector '.item__actions__action--select' should have 1 or fewer BEM elements, but 2 were found  bem-depth
  129:16  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  157:4   error    Selector '.item__actions__action' should have 1 or fewer BEM elements, but 2 were found          bem-depth
  170:25  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals
  175:6   error    Selector '.item__actions__action--select' should have 1 or fewer BEM elements, but 2 were found  bem-depth
  185:27  warning  Color literals such as 'ddd' should only be used in variable declarations                        no-color-literals
  190:6   error    Selector '.item__actions__action--cancel' should have 1 or fewer BEM elements, but 2 were found  bem-depth
  211:17  warning  Color literals such as 'ddd' should only be used in variable declarations                        no-color-literals
  215:6   error    Selector '.item__upload-progress__bar' should have 1 or fewer BEM elements, but 2 were found     bem-depth
  217:19  warning  Color literals such as '29abe2' should only be used in variable declarations                     no-color-literals
  240:12  warning  Color literals such as 'fff' should only be used in variable declarations                        no-color-literals

client/src/containers/Gallery/Gallery.scss
  28:31  warning  Color functions such as 'rgba' should only be used in variable declarations            no-color-literals
  43:27  warning  Color functions such as 'rgba' should only be used in variable declarations            no-color-literals
  69:4   error    Selector '.gallery__load__more' should have 1 or fewer BEM elements, but 2 were found  bem-depth
  71:12  warning  Color literals such as 'fff' should only be used in variable declarations              no-color-literals
  78:23  warning  Color literals such as '338dc1' should only be used in variable declarations           no-color-literals
  86:23  warning  !important not allowed                                                                 no-important
```

/cc @sminnee @clarkepaul

### CODE REVIEW

**Comment by sminnee** [comment]
If we need to use the ruby-based scss-lint in order to integrate with CodeClimate, and we need CodeClimate in order to test only the diffs of CSS while we don't yet have a squeaky-clean CSS codebase, then I can see the argument for introducing scss-lint.

However, that being the case I think we should drop sass-lint altogether, at least for the time being. It performs linting according to a different set of rules, and it will confuse people if we get CSS that works in 1 and breaks in the other.

It's a bit weird, but I'd suggest that `npm run lint` executes the ruby tool, so at least `npm run` is a consistent toolbox of build scripts.

**Comment by chillu** [comment]
Updated with Sam's feedback. Note that `sass-lint` was never part of `npm-shrinkwrap.json` so doesn't need to be removed from there.

**Comment by sminnee** [comment]
Like it.

**Comment by chillu** [comment]
Note that I haven't added scss-lint to `npm run lint`. I couldn't figure out how to conditionally execute a bash command if a binary is available (which we can't assume at this point).

Also, I haven't added a `Gemfile` and `bundler` lock file for scss-lint since I figured that would get a bit comical regarding the amount of package managers we reference in the project root ;) Since `gem` installs globally by default, its not strictly required. And it doesn't look like scss-lint is breaking BC often, so we should be fine with running the latest stable there through a standard `gem scss-lint`.

**Pull request merged**
