### PR TITLE
BUG Correctly process all non-insert form actions normally in the media dialog

### PR DESCRIPTION
**Pull request by tractorcow**
Related to #813

### CODE REVIEW

**Comment by tractorcow** [comment]
Reproduction of issue:

- Enable save / publish action in form builder

```diff
diff --git a/code/Forms/FileFormFactory.php b/code/Forms/FileFormFactory.php
index 2e4f884..d113b5c 100644
--- a/code/Forms/FileFormFactory.php
+++ b/code/Forms/FileFormFactory.php
@@ -66,7 +66,7 @@ class FileFormFactory extends AssetFormFactory
                 $tabs->unshift($this->getFormFieldLinkOptionsTab($record, $context));
                 break;
             case static::TYPE_SELECT:
-                $tabs->setReadonly(true);
+                //$tabs->setReadonly(true);
                 break;
         }

@@ -281,6 +281,8 @@ class FileFormFactory extends AssetFormFactory
         $actionItems = [];
         if ($type === static::TYPE_INSERT_MEDIA || $type === static::TYPE_SELECT) {
             $actionItems = array_filter([
+                $this->getSaveAction($record),
+                $this->getPublishAction($record),
                 $this->getInsertAction($record),
             ]);
         } elseif ($type === static::TYPE_INSERT_LINK) {
```

- Use the uploadfield on any page to select a file in the media library
- Modify a field on any file, and click "save" or "save and publish"
- Expected behaviour: File is saved
- Actual behaviour: Javascript error

**Comment by tractorcow** [comment]
I forgot to build the dist files sorry!

**Comment by tractorcow** [comment]
Looks like it needed a second rebuild.

**Comment by unclecheese** [comment]
LGTM.. can you rebase against 1.3 and retarget, please?

**Comment by tractorcow** [comment]
No problem will do. :D

**Comment by tractorcow** [comment]
@unclecheese rebased and target branch changed. Ta!

**Pull request merged**
