### PR TITLE
MNT Update jest tests for archive text

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-versioned-admin/issues/300

### CODE REVIEW

**Comment by ChloeSartorelli** [comment]
Merge up failed due to merge conflicts: https://github.com/silverstripe/silverstripe-asset-admin/actions/runs/5792638035/job/15699211485
But I don't think that holds this PR up in any way. Please rebase so that the only commit is the new changes.

**Comment by emteknetnz** [comment]
Have rebased

**Comment by ChloeSartorelli** [comment]
Please resolve the merge conflict

**Comment by emteknetnz** [comment]
Resolved

**Review by ChloeSartorelli — APPROVED** [review]
Looks good, works well locally.

**Pull request merged**
