### PR TITLE
Make bulk-actions a 'dumb' component

### PR DESCRIPTION
**Pull request by scott1702**
Also fixes test warning relating to bulk-actions

### CODE REVIEW

**Comment by scott1702** [comment]
Constants issue was fixed here https://github.com/silverstripe/silverstripe-asset-admin/pull/97, this no only affects the bulk action component.

**Comment by chillu** [comment]
Has been superseded by Sam's backend refactoring

**Comment by tractorcow** [comment]
Can we remove that branch now @chillu ?

**Comment by chillu** [comment]
Yep, deleted

**Pull request closed without merging**
