### PR TITLE
NEW: Add extension hook for field-specific validation

### PR DESCRIPTION
**Pull request by lozcalver**
Depends on https://github.com/silverstripe/silverstripe-framework/pull/10569

### CODE REVIEW

**Comment by lozcalver** [comment]
Would I need to update composer.json to `"silverstripe/framework": "^4.12"` as part of this? I seem to remember we used to do that automatically for minor releases, but I think that stopped?

**Comment by michalkleiner** [comment]
> Would I need to update composer.json to `"silverstripe/framework": "^4.12"` as part of this? I seem to remember we used to do that automatically for minor releases, but I think that stopped?

That would be my expectation to require a version that introduced what's used here, unless we update this PR to include a `$this->hasMethod('extendValidationResult')` check.

**Comment by lozcalver** [comment]
Removed the composer.json update as both PRs are now targeting 5.0.0

**Comment by ChloeSartorelli** [comment]
Rebased on top of 2.0 to get rid of the unrelated CI failures.

**Review by ChloeSartorelli — APPROVED** [review]

**Pull request merged**
